spring:
  application:
    name: SBMS_ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gopalkushwah/sbms-config-server-ashok-sir
          clone-on-start: true
          search-paths: config
          default-label: ConfigYmlFiles
          
            
