spring:
  application:
    name: GREET
  config:
    import: optional:configserver:http://localhost:8080
#  cloud:
#    config:
#      uri: http://localhost:8080
#      label: ConfigYmlFiles
    
server:
  port: 8081
  